name: Validate Encodings
description: This action validates all encodings in .mei and .tei-format against the given rng schema.

on: 
  release:
    types: [created] # on creation of release, stop release process if an error occurs

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Validate Encodings Python Script
        run: python validate_encodings.py
