name: Validate Encodings

# on: workflow_dispatch

on: 
  release:
    types: [created] # on creation of release, stop release process if an error occurs
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:

    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install lxml requests
    
    - uses: actions/checkout@v3
    - name: Run Validate Encodings Python Script
      run: python validate_encodings.py ./
